### ISSUE TITLE
Please provide binaries or a Dockerfile for building

### ISSUE THREAD

**Issue by dAnjou** [knq/jwt#1]
Tools like yours have a target audience beyond Go developers. It should be made easy for those to get and use the tool.

Please have a look at my project's [Dockerfile](https://github.com/dAnjou/goup/blob/master/Dockerfile) and [Makefile](https://github.com/dAnjou/goup/blob/master/Makefile) to get an idea of what I'm talking about.

And/Or have a look at [GoReleaser](https://goreleaser.github.io/).

Thanks!

**Comment by kenshaw** [comment]
This is a package. It's not a cli tool. I don't know what "release" for non-Go developers there would be.

**Comment by dAnjou** [comment]
The README says:

> The **command line tool** can be used as follows (assuming jwt is somewhere on $PATH):

**Comment by kenshaw** [comment]
This is a testing tool for the package itself. It would not be useful to those who are not developing the `jwt` source code. For the record, you don't need a Docker image or a Makefile to build a project like this. It's 100% in Go. All that's needed is to have Go installed.

**Comment by dAnjou** [comment]
> This is a testing tool for the package itself. It would not be useful to those who are not developing the jwt source code.

Maybe this should be clarified in the README then.

> For the record, you don't need a Docker image or a Makefile to build a project like this. It's 100% in Go. All that's needed is to have Go installed.

Like I said, not everyone is a Go developer and/or wants to setup a Go environment. But it's likely they already have Docker installed.

**Comment by kenshaw** [comment]
It's not exactly the world's most popular Go package ... :-)
